version: "3"

services:
  proxy:
    build:
      context: ./proxy/
      dockerfile: Dockerfile-proxy
    ports:
      - 80:80
      - 443:443

  app:
    build:
      context: ./server/
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      OPENAI_SECRET: ${OPENAI_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    links:
      - db

  db:
    image: scylladb/scylla
