version: "3"

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    ports:
      - 443:443

  app:
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    links:
      - db

  db:
    image: scylladb/scylla
