[package]
name = "sched-bird"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
anyhow = "1.0.71"
tokio = { version = "1.28.1", features = ["full"] }
axum = { version = "0.6.18" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["full"] }
tower-cookies = "0.9.0"
scylla = { version = "0.8.1" }
oauth2 = { version = "4.4.0" }
url = { version = "2.2.0" }
http-body = "0.4.5"
openssl-probe = "0.1.5"
octocrab = "0.23.0"
yew = { version = "0.20.0", features = ["ssr"] }
chrono = "0.4.26"
